remove pure variables
mgudemann/sat-solver pull request #1
Opened 2021-11-18 21:22 UTC by AndHager

Implemented a function that removes at the begin of cdcl all pure variables and assigns values to them.
This modification improves the performance of the cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_60_178.cnf bench from around 300  to 4 seconds.

2021-11-18 22:17 UTC, mgudemann requested changes

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Types.hs
> +    show BNothing = "Noting"
please revert, unrelated change

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Types.hs
> +
please revert, unrelated change

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Algorithm.hs
> -
please remove whitespace changes

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Algorithm.hs
> +            where (reducedTerm, pureVars) = rmPureVars clist
please align all `->`

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Algorithm.hs
> +                --                       ]
please keep to line comments in type signature

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/Algorithm.hs
> +  -> CDCLResult -- result
please use haddock style documentation for type signature, i.e.,
```
-> Int -- ^ The 'Int' argument
-> ...
```

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/DPLL.hs
> +rmPureVars :: [[Integer]] -> ([[Integer]], [Int])
please add haddock documentation for functions (at least for exported ones)

2021-11-18 22:17 UTC, mgudemann commented on src/CDCL/DPLL.hs
> +containsVar (x:xs) var = (x == var) || containsVar xs var
use `Data.List.notElem` instead

2021-11-18 22:54 UTC, mgudemann commented
please rebase onto `main`

2021-11-18 22:59 UTC, mgudemann commented
#2 removed output of satisfying valuation, reducing the size of output for larger SAT instances
Could you provide some more benchmarks for `opt` after rebase? `stack test` is slower with `opt` but that may be irrelevant.

2021-11-19 13:40 UTC, AndHager commented
Benchmarks of the unmodified sat-solver:
Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_10_17.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_102_481.cnf
Result: SAT
CPU time:   1.67s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_108_345.cnf
Result: SAT
CPU time:   0.28s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_112_238.cnf
Result: SAT
CPU time:   0.07s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_117_328.cnf
Result: SAT
CPU time:   0.35s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_120_1016.cnf
Result: SAT
CPU time:  16.30s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_120_724.cnf
Result: SAT
CPU time:   0.86s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_12_16.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_130_393.cnf
Result: SAT
CPU time:   0.32s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_135_510.cnf
Result: SAT
CPU time: 700.95s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_140_1371.cnf
Result: SAT
CPU time:   1.99s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_14_19.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_144_648.cnf
Result: SAT
CPU time:   2.84s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_15_23.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_153_714.cnf
Result: SAT
CPU time:   0.22s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_160_1028.cnf
Result: SAT
CPU time:  10.80s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_16_24.cnf
Result: SAT
CPU time:   0.01s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_168_722.cnf
Result: SAT
CPU time:   3.01s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_170_1247.cnf
Result: SAT
CPU time:   3.34s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_18_21.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_18_49.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_185_1132.cnf
Result: SAT
CPU time:  13.91s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_195_899.cnf
Result: SAT
CPU time:   8.78s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_196_1092.cnf
Result: SAT
CPU time: 295.45s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_210_1275.cnf
Result: SAT
CPU time:   8.52s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_21_40.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_222_1477.cnf
Result: SAT
CPU time:  60.85s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_228_3437.cnf
Result: SAT
CPU time:  10.39s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_24_34.cnf
Result: SAT
CPU time:   0.05s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_24_56.cnf
Result: SAT
CPU time:   0.04s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_252_3132.cnf
Result: SAT
CPU time: 6166.78s

2021-11-19 13:40 UTC, AndHager commented
Benchmarks of the modified sat-solver:
Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_10_17.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_102_481.cnf
Result: SAT
CPU time:   0.22s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_108_345.cnf
Result: SAT
CPU time:   0.09s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_112_238.cnf
Result: SAT
CPU time:   0.17s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_117_328.cnf
Result: SAT
CPU time:   0.12s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_120_1016.cnf
Result: SAT
CPU time:  54.91s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_120_724.cnf
Result: SAT
CPU time:   2.26s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_12_16.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_130_393.cnf
Result: SAT
CPU time:   0.09s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_135_510.cnf
Result: SAT
CPU time:   4.61s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_140_1371.cnf
Result: SAT
CPU time:   1.12s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_14_19.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_144_648.cnf
Result: SAT
CPU time:   0.34s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_15_23.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_153_714.cnf
Result: SAT
CPU time:   0.60s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_160_1028.cnf
Result: SAT
CPU time:   0.46s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_16_24.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_168_722.cnf
Result: SAT
CPU time:   0.39s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_170_1247.cnf
Result: SAT
CPU time:   0.97s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_18_21.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_18_49.cnf
Result: SAT
CPU time:   0.16s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_185_1132.cnf
Result: SAT
CPU time:   9.74s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_195_899.cnf
Result: SAT
CPU time:   0.60s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_196_1092.cnf
Result: SAT
CPU time:  46.84s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_210_1275.cnf
Result: SAT
CPU time:   0.23s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_21_40.cnf
Result: SAT
CPU time:   0.16s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_222_1477.cnf
Result: SAT
CPU time:  53.41s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_228_3437.cnf
Result: SAT
CPU time:   3.19s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_24_34.cnf
Result: SAT
CPU time:   0.00s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_24_56.cnf
Result: SAT
CPU time:   0.03s

Executing: cadp.inria.fr/ftp/benchmarks/vlsat/vlsat1_252_3132.cnf
Result: SAT
CPU time:  72.82s

2021-11-19 14:51 UTC, merged

2021-11-19 15:09 UTC, mgudemann commented
@AndHager LGTM

#3 seems to be a fallout from this