Reproduced and fixed Issue #5
mgudemann/sat-solver pull request #10
Opened 2022-02-24 12:03 UTC by AndHager

Closes #5.
Reproduced and solved #5. 
Added variable assignment from pure var reduction to the result TupleList.

2022-02-24 14:30 UTC, mgudemann requested changes

2022-02-24 14:30 UTC, mgudemann commented on test/AlgorithmSpec.hs
> +            resultAssignment`shouldBe` [2, -1]
hier stimmt was nicht ganz. Die Message unterscheidet sich vom Zielwert. Das problem ist auch analog wie oben. Vermutlich Copy&Paster error?

2022-02-25 09:02 UTC, AndHager commented on test/AlgorithmSpec.hs
> +            resultAssignment`shouldBe` [2, -1]
Ja das ist ein Copy&Paste error.

2022-02-25 09:47 UTC, mgudemann approved these changes
LGTM

2022-02-25 09:47 UTC, merged